site_name: Awesome MCP FastAPI
site_description: A comprehensive FastAPI implementation of the Model Control Plane
site_author: Your Name
site_url: https://your-domain.com/docs

# Repository
repo_name: awesome-mcp-fastapi
repo_url: https://github.com/yourusername/awesome-mcp-fastapi
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Your Name

# Configuration
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - social:
      cards_dir: assets/images/social

# Page navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - Concepts:
    - Tool Registry: concepts/tool-registry.md
  - Guides:
    - guide1: guides/guide1.md
  - API Reference:
    - api_doc1: api-reference/api_doc1.md
  - Comparison:
    - vs Standard MCP: comparison/vs-standard-mcp.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourusername

extra_css:
  - css/extra.css